In [45]:
print()
print("="*72)
print(f"|{'Welcome to mini project by RAMESH'.center(70,'-')}|")
print("="*72)

import pymysql as sql
from pymysql import ProgrammingError #imported this to use this dberror exception
from pymysql import OperationalError #imported this to use this dberror exception
connection = sql.connect(host="127.0.0.1",user="root",port=3306)
crsr = connection.cursor()
try:
    print("\n1.List of Databases\n2.Update Database\n3.Create Database\n4.Delete Database\n5.Exit Application")
    while True:
        choice = input("Enter your choice : ")
        if choice == '1':
            crsr.execute("show databases")
            databases = crsr.fetchall()
            print()
            print("-"*29)
            for row in databases:
                print("|  "+row[0].ljust(25)+"|")
            print("-"*29)

        elif choice == '2':
            try:
                cmd = input("Enter name of database to use : ")
                crsr.execute(f"use {cmd}")
            except OperationalError:
                print("Entered database does not exist !!!")
            except Exception as e:
                print(f"Error Found : {e}")
            
            print("\n1.List of tables\n2.Create Table\n3.Update Table\n4.Fetch Table Data\n5.Go Back")
            while True:
                tbl_choice = input("Enter your choice to update selected database : ")
                if tbl_choice == '1':
                    crsr.execute("show tables")
                    databases = crsr.fetchall()
                    print()
                    print("-"*29)
                    for row in databases:
                        print("|  "+row[0].ljust(25)+"|")
                    print("-"*29)
                
                elif tbl_choice == '2':
                    try:
                        tbl_name = input("Enter the name of the new table : ")
                        ttl_columns = int(input("Enter the number of columns: "))
                        columns = []
                        for i in range(ttl_columns):
                            col_name = input("Enter column name : ")
                            col_type = input("Enter column data type (e.g., INT, VARCHAR(255)), with constraints : ")
                            columns.append(f"{col_name} {col_type}")
                        str_col = ", ".join(columns)
                        crsr.execute(f"create table {tbl_name} ({str_col})")
                        print("Table created successfully!!!")
                    except OperationalError:
                        print("Entered table already exist !!!")
                    except Exception as e:
                        print(f"Error Found: {e}")

                elif tbl_choice == '3':
                    try:
                        tbl_name = input("Enter the name of the table to update : ")

                        print("\n1.Add New Column\n2.Delete Existing Column\n3.Delete Row\n4.Add Row\n5.Go Back")
                        tbl_update_choice = input("Enter your choice: ")

                        if tbl_update_choice == '1':
                            new_col_name = input("Enter the name of the new column : ")
                            new_col_datatype = input("Enter the data type for the new column (e.g., VARCHAR(255), INT) : ")
                            crsr.execute(f"alter table {tbl_name} add column {new_col_name} {new_col_datatype}")
                            print(f"Table updated successfully !!!")

                        elif tbl_update_choice == '2':
                            col_to_delete = input("Enter the name of the column to delete : ")
                            crsr.execute(f"alter table {tbl_name} drop column {col_to_delete}")
                            print(f"Column deleted successfully !!!")

                        elif tbl_update_choice == '3':
                            col_id_to_delete = input("Enter the column name for condition to delete : ")
                            value_at_row = input("Enter value row in the entered column : ")
                            crsr.execute(f"delete from {tbl_name} where {col_id_to_delete} = '{value_at_row}'")
                            print(f"Row deleted from table sucessfully !!!")

                        elif tbl_update_choice == '4':
                            try:
                                print("It is sensitive data, insert it carefully.")
                                tbl_name = input("Enter table name : ")
                                tbl_columns = input("Enter column names without inverted cotts : ").split()
                                columns = " ,".join(tbl_columns)
                                row_values = input("Enter all data here (string in inverted cotts ex - 'ram'): ").split()
                                values = " ,".join(row_values)###########doubttt input without inverted cotts
                                crsr.execute(f"insert into {tbl_name}({columns}) values({values})")
                            except OperationalError:
                                print("Entries does not match !!!")
                            except Exception as e:
                                print(f"Error Found : {e}")
                                
                        elif tbl_update_choice == '5':
                            pass

                        else:
                            print("Invalid Input")

                    except ProgrammingError:
                        print("Entered table does not exist!")
                    except Exception as e:
                        print(f"Error Found : {e}")


                elif tbl_choice == '4':
                    try:
                        tbl_name = input("Enter the name of the table to fetch data from: ")
                        crsr.execute(f"select * from {tbl_name}")
                        tbl_data = crsr.fetchall()
                        if tbl_data:
                            print()
                            for row in tbl_data:
                                for col in row:
                                    print(f"  {col:<14}|", end="")
                                print()
                        else:
                            print("No data found !!!")
                    except ProgrammingError:
                        print(f"Table {tbl_name} does not exist!")
                    except Exception as e:
                        print(f"Error Found : {e}")
                elif tbl_choice == '5':
                    break

                else:
                    print("Invalid Input")

        elif choice == '3':
            try:
                print()
                crsr.execute(f"create database {input('Enter name of new database : ')}")
                print("Database created successfully !!!")
            except ProgrammingError:
                print("\nEntered database name already exist !!!")
            except Exception as e:
                print(f"Error Found : {e}")
                
                
        elif choice == '4':
            try:
                print()
                crsr.execute(f"drop database {input('Enter name of database : ')}")
                print("Database drop successfully !!!")
            except OperationalError:
                print("Entered database does not exixt !!!")
            except Exception as e:
                print(f"Error Found : {e}")
        elif choice == '5':
            print("Thanks for using our service")
            break
        else:
            print("Invalid Input")
except Exception as e:
    print(f"Error Found : {e}")
connection.commit()
connection.close()

========================================================================
|------------------Welcome to mini project by RAMESH-------------------|
========================================================================

1.List of Databases
2.Update Database
3.Create Database
4.Delete Database
5.Exit Application
Enter your choice : 1

-----------------------------
|  information_schema       |
|  institute                |
|  mysql                    |
|  performance_schema       |
|  phpmyadmin               |
|  ram2                     |
|  student                  |
-----------------------------
Enter your choice : 2
Enter name of database to use : student

1.List of tables
2.Create Table
3.Update Table
4.Fetch Table Data
5.Go Back
Enter your choice to update selected database : 1

-----------------------------
|  company                  |
|  ram                      |
|  ramji                    |
|  student                  |
-----------------------------
Enter your choice to update selected database : 4
Enter the name of the table to fetch data from: student
No data found !!!
Enter your choice to update selected database : company
Invalid Input
Enter your choice to update selected database : 4
Enter the name of the table to fetch data from: company

  1             |  ramesh        |  pass          |
  2             |  dhruv         |  pass          |
  3             |  bhooumi       |  pass          |
  4             |  unknown       |  fail          |
  5             |  dinesh        |  semi          |
  6             |  jhilmil       |  pass          |
  7             |  madhav        |  pass          |
  8             |  anurag        |  semi          |
  10            |  kbu           |  pass          |
  10            |  kbu           |  pass          |
  10            |  kbu           |  5             |
  10            |  456           |  5             |
  4             |  456           |  5             |
  0             |  456           |  5             |
Enter your choice to update selected database : 5
Enter your choice : 5
Thanks for using our service